Fixed a bug and added an option in csv-cut.
Bug:
  csv-cut could find matches in header, resulting in the header
  being output twice.  Added option to ignore rows to fix this.
Option:
  -v reverse matches.

diff --git a/csv-grep b/csv-grep
--- a/csv-grep
+++ b/csv-grep
@@ -3,7 +3,7 @@ SRCDIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 
 DELIM=','
 QUO='"'
-while getopts h?d:f:c:p:r: OPT; do
+while getopts h?d:f:c:p:r:v? OPT; do
     case $OPT in
         \?|h)
             echo "csv-grep: select rows from a csv acocrding to a pattern."
@@ -30,31 +30,39 @@ while getopts h?d:f:c:p:r: OPT; do
         p)
             PATTERN=$OPTARG
             ;;
+        v)
+            REVERSEMATCH=1
+            ;;
     esac
 done
 
 if [[ $FILE == '' ]]; then
-  echo "csv-grep: Argument -f required." >&2
-  exit 1
+    echo "csv-grep: Argument -f required." >&2
+    exit 1
 fi
 
 if [[ $COL == '' ]]; then
-  echo "csv-grep: Argument -c required." >&2
-  exit 1
+    echo "csv-grep: Argument -c required." >&2
+    exit 1
 fi
 
 if [[ $PATTERN == '' ]]; then
-  echo "csv-grep: Argument -p required." >&2
-  exit 1
+    echo "csv-grep: Argument -p required." >&2
+    exit 1
 fi
-
+# Reverse match is optional.
+if [[ $REVERSEMATCH == '' ]]; then
+    REVERSEMATCH=0
+fi
 # Header argument is optional, if not supplied it is assumed to be the 
-# first line in FILE
+# first line in FILE.
 if [[ $HEADERFILE == '' ]]; then
     HEADERFILE=$FILE
     HEADER=$(cat $FILE | head -1)
+    NROWTOSKIP=1
 else
     HEADER=$(cat $HEADERFILE)
+    NROWTOSKIP=0
 fi
 
 # Check if the column array is numeric id's, if not, parse the array of names
@@ -75,9 +83,9 @@ if [[ $HEADERFILE == $FILE ]]; then
 fi
 # Call the binary.
 if [[ $QUO == '"' ]]; then
-    $SRCDIR/bin/grep $FILE $DELIM '"' $COLIDX $PATTERN
+    $SRCDIR/bin/grep $FILE $DELIM '"' $NROWTOSKIP $REVERSEMATCH $COLIDX $PATTERN
 elif [[ $QUO == "'" ]]; then
-    $SRCDIR/bin/grep $FILE $DELIM "'" $COLIDX $PATTERN
+    $SRCDIR/bin/grep $FILE $DELIM "'" $NROWTOSKIP $REVERSEMATCH $COLIDX $PATTERN
 else
-    $SRCDIR/bin/grep $FILE $DELIM $QUO $COLIDX $PATTERN
+    $SRCDIR/bin/grep $FILE $DELIM $QUO $NROWTOSKIP $REVERSEMATCH $COLIDX $PATTERN
 fi
