Add some features to csv-grep
  - Use a seperate header file with -r option.
  - Use numeric column index.

diff --git a/csv-grep b/csv-grep
--- a/csv-grep
+++ b/csv-grep
@@ -3,13 +3,13 @@ SRCDIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 
 DELIM=','
 QUO='"'
-while getopts h?d:f:c:p: OPT; do
+while getopts h?d:f:c:p:r: OPT; do
     case $OPT in
         \?|h)
             echo "csv-grep: select rows from a csv acocrding to a pattern."
             echo "useage:"
-            echo "  csv-grep -f <delimited file> [-d <delim>] [-q <quoting char>]"
-            echo "           -c <column name> -p <pattern>"
+            echo "  csv-grep -f <delimited file> [-d <delim>] [-q <quoting char>]"\
+                 "[-r <header file>] -c <column name or index> -p <pattern>"
             exit 0
             ;;
         d)
@@ -21,6 +21,9 @@ while getopts h?d:f:c:p: OPT; do
         f)
             FILE=$OPTARG
             ;;
+        r)
+            HEADERFILE=$OPTARG
+            ;;
         c)
             COL=$OPTARG
             ;;
@@ -30,22 +33,51 @@ while getopts h?d:f:c:p: OPT; do
     esac
 done
 
-COLIDX=$(csv-getcolidx -f $FILE -d $DELIM -c $COL)
-if [[ $? != 0 ]]; then
-    exit 1
+if [[ $FILE == '' ]]; then
+  echo "csv-grep: Argument -f required." >&2
+  exit 1
 fi
 
+if [[ $COL == '' ]]; then
+  echo "csv-grep: Argument -c required." >&2
+  exit 1
+fi
+
+if [[ $PATTERN == '' ]]; then
+  echo "csv-grep: Argument -p required." >&2
+  exit 1
+fi
+
+# Header argument is optional, if not supplied it is assumed to be the 
+# first line in FILE
+if [[ $HEADERFILE == '' ]]; then
+    HEADERFILE=$FILE
+    HEADER=$(cat $FILE | head -1)
+else
+    HEADER=$(cat $HEADERFILE)
+fi
+
+# Check if the column array is numeric id's, if not, parse the array of names
+# to get the numeric indicies of the named columns
+if [[ $COL =~ [0-9] ]]; then
+    COLIDX=$COL
+else
+    COLIDX=$(csv-getcolidx -f $HEADERFILE -d $DELIM -c $COL)
+    if [[ $? != 0 ]]; then
+        echo "csv-grep: Could not find indicies for some of the requested columns." >&2
+        echo "Are you sure they all exist?" >&2
+        exit 1
+    fi
+fi
+
+if [[ $HEADERFILE == $FILE ]]; then
+    echo $HEADER
+fi
 # Call the binary.
 if [[ $QUO == '"' ]]; then
-    { cat $FILE | head -1 ; \
-      $SRCDIR/bin/grep $FILE $DELIM '"' $COLIDX $PATTERN
-    }
+    $SRCDIR/bin/grep $FILE $DELIM '"' $COLIDX $PATTERN
 elif [[ $QUO == "'" ]]; then
-    { cat $FILE | head -1 ; \
-      $SRCDIR/bin/grep $FILE $DELIM "'" $COLIDX $PATTERN
-    }
+    $SRCDIR/bin/grep $FILE $DELIM "'" $COLIDX $PATTERN
 else
-    { cat $FILE | head -1 ; \
-      $SRCDIR/bin/grep $FILE $DELIM $QUO $COLIDX $PATTERN
-    }
+    $SRCDIR/bin/grep $FILE $DELIM $QUO $COLIDX $PATTERN
 fi
