Check for all required arguments.

diff --git a/csv-chdelim b/csv-chdelim
--- a/csv-chdelim
+++ b/csv-chdelim
@@ -26,6 +26,19 @@ while getopts h?d:n:q:f: OPT; do
     esac
 done
 
+if [[ $FILE == '' ]]; then
+    echo "csv-chdelim: Argument -f required." >&2
+    exit 1
+fi
+if [[ $DELIM == '' ]]; then
+    echo "csv-chdelim: Argument -d required." >&2
+    exit 1
+fi
+if [[ $NEWDELIM == '' ]]; then
+    echo "csv-chdelim: Argument -n required." >&2
+    exit 1
+fi
+
 if [[ $QUO == '"' ]]; then
    $SRCDIR/bin/chdelim $FILE $DELIM $NEWDELIM '"'
 elif [[ $QUO == "'" ]]; then
diff --git a/csv-getcolidx b/csv-getcolidx
--- a/csv-getcolidx
+++ b/csv-getcolidx
@@ -22,6 +22,15 @@ while getopts h?f:d:c: OPT; do
     esac
 done
 
+if [[ $FILE == '' ]]; then
+    echo "csv-getcolidx: argument -f required" >&2
+    exit 1
+fi
+if [[ $COL == '' ]]; then
+    echo "csv-getcolidx: argument -c required" >&2
+    exit 1
+fi
+
 COLIDX=$(head -1 $FILE | sed "s!$DELIM!\n!g" | grep -nx $COL | cut -d: -f 1)
 
 if [[ $COLIDX == '' ]]; then
@@ -29,5 +38,6 @@ if [[ $COLIDX == '' ]]; then
     exit 1
 fi
 
+# grep -n counts starting at one, we require starting at 0.
 echo "$COLIDX - 1" | bc
 exit 0
diff --git a/csv-getcolidxs b/csv-getcolidxs
--- a/csv-getcolidxs
+++ b/csv-getcolidxs
@@ -1,6 +1,5 @@
 #! /bin/bash
 
-# Parse command line args
 DELIM=','
 while getopts h?f:d:c: OPT; do
     case $OPT in
@@ -19,20 +18,34 @@ while getopts h?f:d:c: OPT; do
     esac
 done
 
+if [[ $FILE == '' ]]; then
+    echo "csv-getcolidxs: Argument -f required." >&2
+    exit 1
+fi
+
 # Shift the argument pointer so that the passed coumns are stored in $1, $2, etc
 shift $(($OPTIND - 1))
 
-out_str=""
-for COLNM in ${@:1}; do
-  COLIDX=$(csv-getcolidx -d $DELIM -f $FILE -c $COLNM)
+COLS="${@:1}"
+if [[ $COLS == '' ]]; then
+    echo "csv-cut: No columns to cut" >&2
+    exit 1
+fi
+OUTSTR=""
 
+# Iteratively get the index of the columns requested, and join them into
+# a comma seperated string.
+for COLNM in $COLS; do
+  COLIDX=$(csv-getcolidx -d $DELIM -f $FILE -c $COLNM)
   if [[ $? != 0 ]]; then
       echo "csv-getcolidxs: Field $COLNM not found, terminating."
       exit 1
   fi
-
-  out_str="$out_str,$COLIDX"
+  OUTSTR="$OUTSTR,$COLIDX"
 done;
 
-echo $out_str | sed "s/,//" | sed "s/,/ /g"
+# Replace the beginning comma with nothing (fencepost problem), replace
+# all remaining commas with spaces to make a nice argument list for a 
+# command line call.
+echo $OUTSTR | sed "s/,//" | sed "s/,/ /g"
 exit 0
diff --git a/csv-hist b/csv-hist
--- a/csv-hist
+++ b/csv-hist
@@ -6,8 +6,8 @@ while getopts h?d:f:c:p: OPT; do
         \?|h)
             echo "csv-hist: Make a frequency table from columns in a csv."
             echo "useage:"
-            echo "  csv-grep -f <delimited file> [-d <delim>] [-q <quoting char>]"
-            echo "           <column 1 name> ... <column n name>                 "
+            echo "  csv-hist -f <delimited file> [-d <delim>] [-q <quoting char>]"\
+                 "<column 1 name> ... <column n name>                 "
             exit 0
             ;;
         d)
@@ -22,9 +22,19 @@ while getopts h?d:f:c:p: OPT; do
     esac
 done
 
-shift $(($OPTIND - 1))
+if [[ $FILE == '' ]]; then
+    echo "csv-hist: Argument -f required." >&2
+    exit 1
+fi
 
-csv-cut -f $FILE -d $DELIM -q $QUO ${@:1} \
+shift $(($OPTIND - 1))
+COLS="${@:1}"
+if [[ $COLS == '' ]]; then
+    echo "csv-hist: No columns to summarize." >&2
+    exit 1
+fi
+
+csv-cut -f $FILE -d $DELIM -q $QUO $COLS \
   | tail -n +2 \
   | sort \
   | uniq -c
diff --git a/csv-sample b/csv-sample
--- a/csv-sample
+++ b/csv-sample
@@ -1,16 +1,13 @@
 #! /bin/bash
 
 DELIM=','
-while getopts h?d:f:p: OPT; do
+while getopts h:f:p: OPT; do
     case $OPT in
         \?|h)
             echo "csv-sample: Randomly sample a proportion of a data set."
             echo "useage:"
             echo "  csv-sample -f <delimited file> [-d <delim>] -p <proportion>"
             exit 0
-            ;;
-        d)
-            DELIM=$OPTARG
             ;;
         f)
             FILE=$OPTARG
@@ -20,6 +17,15 @@ while getopts h?d:f:p: OPT; do
             ;;
     esac
 done
+
+if [[ $FILE == '' ]]; then
+    echo "csv-sample: Argument -f required." >&2
+    exit 1
+fi
+if [[ $PROP == '' ]]; then
+    echo "csv-sample: Argument -p required." >&2
+    exit 1
+fi
 
 NREC=$(cat $FILE | tail -n +2 | wc -l)
 NTOTAKE=$(echo "$NREC * $PROP" | bc -l | cut -d. -f1)
