Error handling in csv-getcolidx?

diff --git a/csv-getcolidx b/csv-getcolidx
--- a/csv-getcolidx
+++ b/csv-getcolidx
@@ -22,4 +22,12 @@ while getopts h?f:d:c: OPT; do
     esac
 done
 
-head -1 $FILE | sed "s!$DELIM!\n!g" | grep -nx $COL | cut -d: -f 1 
+COLIDX=$(head -1 $FILE | sed "s!$DELIM!\n!g" | grep -nx $COL | cut -d: -f 1)
+
+if [[ $COLIDX == '' ]]; then
+    echo "csv-getcolidx: Column $COL not found.  Terminating." >&2
+    exit 1
+fi
+
+echo "$COLIDX - 1" | bc
+exit 0
diff --git a/csv-getcolidxs b/csv-getcolidxs
--- a/csv-getcolidxs
+++ b/csv-getcolidxs
@@ -23,7 +23,16 @@ done
 shift $(($OPTIND - 1))
 
 out_str=""
-for i in ${@:1}; do
-  out_str="$out_str,$(csv-getcolidx -d $DELIM -f $FILE -c $i)"
+for COLNM in ${@:1}; do
+  COLIDX=$(csv-getcolidx -d $DELIM -f $FILE -c $COLNM)
+
+  if [[ $? != 0 ]]; then
+      echo "csv-getcolidxs: Field $COLNM not found, terminating."
+      exit 1
+  fi
+
+  out_str="$out_str,$COLIDX"
 done;
-echo $out_str | sed "s/,//"
+
+echo $out_str | sed "s/,//" | sed "s/,/ /g"
+exit 0
